config:
    required: true

database:
    +:
        name: default
        namespace: Creonit\UserBundle\Model
        defaultIdMethod: native

    +behavior:
        - \Creonit\UserBundle\Behavior\UserBehavior

    user_sign:
        id: int pk > user.id
        provider: varchar(20) pk
        username: varchar(128) pk
        password: varchar(64)
        secret: varchar(64)
        enabled: boolean = 0

    user_group:
        title: text
        name: varchar(50) key(10)
        +behavior: [tree, {sortable: portable}]

    user_group_rel:
        user_id: int > user.id
        group_id: int > user_group.id

    user_role_group:
        title: text
        +behavior: [sortable]

    user_role:
        group_id: int > user_role_group.id
        title: text
        name: varchar(50) key(10)
        +behavior: [{sortable: group_id}]

    user_group_role:
        group_id: int > user_group.id
        role_id: int > user_role.id
        rule: tinyint